// Per-course certification badge, scraped from the matching simpliaxis page.
// Manifest is generated by scripts/scrape-badges.sh (re-run to refresh).
// Any course without a scraped badge falls back to the "UL" default.
import manifest from "./badge-manifest.json";

export const DEFAULT_BADGE = "/images/courses/badges/_default-ul.svg";

export function courseBadge(slug: string): string {
  return (manifest as Record<string, string>)[slug] ?? DEFAULT_BADGE;
}
